default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ibarbosa_development
test:
  <<: *default
  database: ibarbosa_test
production:
  <<: *default
  database: ibarbosa_production
  username: natus
  password: <%= ENV['NATUS_DATABASE_PASSWORD'] %>
